import express from 'express';
import 'express-async-errors';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import { Pool } from 'pg';
import { randomUUID } from 'crypto';
import { WebSocketServer } from 'ws';
import http from 'http';
import { trace } from '@opentelemetry/api';
import { requests, duration, metricsText } from './infrastructure/observability/metrics.js';
import { createRealtime } from './infrastructure/realtime/websocket.js';
import { registerAuthRoutes } from './domains/auth/routes.js';
import { registerAccountRoutes } from './domains/account/routes.js';
import { registerGroupRoutes } from './domains/group/routes.js';
import { registerSequenceRoutes } from './domains/sequence/routes.js';
import { startSequenceWorker } from './domains/sequence/worker.js';
import { startAgentProcessor } from './domains/agent/processor.js';
import { startGroupJobs } from './domains/group/jobs.js';
import { startOutbox } from './domains/message/outbox.js';
import { startMediaWorker } from './domains/message/media.js';
import { startGatewayConsumer } from './infrastructure/events/consumer.js';
const app=express();
const server=http.createServer(app);
const wss=new WebSocketServer({server,path:'/ws'});
const pool=new Pool({connectionString:process.env.DATABASE_URL||'postgresql://sentinel:sentinel@localhost:5432/sentinel'});
const PORT=Number(process.env.PORT||4000);
const JWT_SECRET=process.env.JWT_SECRET||'dev-secret';
if(process.env.NODE_ENV==='production'&&(!process.env.JWT_SECRET||process.env.JWT_SECRET.length<32))throw new Error('JWT_SECRET must contain at least 32 characters in production');
const GATEWAY=process.env.GATEWAY_URL||'http://localhost:4001';
const AGENT=process.env.AGENT_URL||'http://localhost:4002';
const allowedOrigins=new Set((process.env.CORS_ORIGINS||'http://127.0.0.1:5173,http://localhost:5173').split(',').map(value=>value.trim()));
app.use(cors({origin:(origin,callback)=>callback(null,!origin||allowedOrigins.has(origin)),credentials:true}));
app.use(express.json());
app.use(cookieParser());
const broadcast=createRealtime(pool,JWT_SECRET,wss);
app.use((req:any,res,next)=>{
  const suppliedRequestId=req.headers['x-request-id'];
  req.requestId=typeof suppliedRequestId==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(suppliedRequestId)?suppliedRequestId:randomUUID();
  req.traceId=trace.getActiveSpan()?.spanContext().traceId||req.headers['x-trace-id']||randomUUID();
  req.ogId=req.headers['x-og-id']||null;
  res.setHeader('x-request-id',req.requestId);
  res.setHeader('x-trace-id',req.traceId);
  const started=performance.now();
  res.on('finish',()=>{
    const seconds=(performance.now()-started)/1000;
    const route=req.route?.path ? `${req.baseUrl}${req.route.path}` : 'unmatched';
    requests.inc({method:req.method,route,status:String(res.statusCode)});
    duration.observe({method:req.method,route},seconds);
    console.log(JSON.stringify({event:'http_request',service:'backend',requestId:req.requestId,traceId:req.traceId,ogId:req.ogId,method:req.method,path:req.path,status:res.statusCode,durationMs:Math.round(seconds*1000),userId:req.user?.sub||null}));
  });
  next();
});
app.get('/api/metrics',async(_req,res)=>{try{res.type('text/plain').send(await metricsText(pool))}catch(error){res.status(503).json({error:String(error)})}});
const {auth,write}=registerAuthRoutes(app,pool,JWT_SECRET);
app.get('/api/health',async(_req,res)=>{try{await pool.query('SELECT 1');res.json({ok:true,schemaVersion:'1.3.0'})}catch{res.status(503).json({ok:false,schemaVersion:'unknown'})}});
registerAccountRoutes(app,pool,GATEWAY,broadcast,auth,write);
registerGroupRoutes(app,pool,broadcast,auth,write);
registerSequenceRoutes(app,pool,auth,write);
app.use('/api',(req:any,res)=>res.status(404).json({error:{code:'NOT_FOUND',message:'接口不存在',requestId:req.requestId}}));
app.use((error:any,req:any,res:any,_next:any)=>{
  const validation=error instanceof SyntaxError && 'body' in error;
  const status=validation?400:503;
  const code=validation?'VALIDATION_ERROR':'INTERNAL_ERROR';
  console.error(JSON.stringify({event:'request_failed',requestId:req.requestId,traceId:req.traceId,error:String(error),stack:process.env.NODE_ENV==='production'?undefined:error?.stack}));
  if(!res.headersSent)res.status(status).json({error:{code,message:validation?'无效的 JSON 请求体':'服务暂时不可用',requestId:req.requestId}});
});
(async()=>{
  try{
    const schema=await pool.query("SELECT 1 FROM schema_migrations WHERE version='1.3.0'");
    if(!schema.rowCount)throw new Error('schema is behind code; run npm run migrate');
    await startSequenceWorker(pool,broadcast);
    startGroupJobs({pool,gatewayUrl:GATEWAY,publish:broadcast});
    startOutbox(pool,GATEWAY,broadcast);
    startMediaWorker(pool,GATEWAY);
    startAgentProcessor({pool,agentUrl:AGENT,gatewayUrl:GATEWAY,publish:broadcast});
    startGatewayConsumer({pool,gatewayUrl:GATEWAY,publish:broadcast});
    server.listen(PORT,()=>console.log(`backend listening ${PORT}`));
  }catch(error){console.error(JSON.stringify({event:'startup_failed',error:String(error)}));process.exit(1)}
})();
