import { Button } from './components/ui/button';
import { Input } from './components/ui/input';
import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { client, clearSession, currentSession, errorText, setSession } from './api/client';
import type { Account, AgentRun, Group, Message } from './generated';
import { useEvents } from './hooks/useEvents';
import { GroupCreation } from './components/GroupCreation';
import { SequencePanel } from './components/SequencePanel';
import './style.css';

function Login({ onReady }: { onReady: () => void }) {
  const [username, setUsername] = useState('admin'); const [password, setPassword] = useState('admin'); const [error, setError] = useState('');
  return <main className="login"><div className="brand">SENTINEL</div><h1>控制台登录</h1><label>用户名<Input value={username} onChange={e => setUsername(e.target.value)} /></label><label>密码<Input type="password" value={password} onChange={e => setPassword(e.target.value)} /></label><Button onClick={async () => { try { const response = await client.login({ loginRequest: { username, password } }); setSession(response.accessToken); onReady(); } catch (e) { setError(await errorText(e)); } }}>登录</Button>{error && <p className="error">{error}</p>}<small>admin/admin · viewer/viewer</small></main>;
}
function Accounts({ canWrite, onChanged }: { canWrite: boolean; onChanged: () => void }) {
  const [items, setItems] = useState<Account[]>([]); const [error, setError] = useState(''); const load = () => client.listAccounts().then(setItems).catch(async e => setError(await errorText(e)));
  useEffect(() => { load(); }, []);
  async function act(id: string, action: 'connect' | 'disconnected' | 'idle', current: string) { try { if (action === 'connect') await client.connectAccount({ id }); else await client.transitionAccount({ id, transitionRequest: { to: action, expectedFrom: current } }); load(); onChanged(); } catch (e) { setError(await errorText(e)); } }
  return <section><div className="section-title"><h2>账号</h2><Button className="subtle" onClick={load}>刷新</Button></div>{error && <p className="error">{error}</p>}<div className="grid">{items.map(item => <article key={item.id}><div className="row"><b>{item.id}</b><span className={`status ${item.status}`}>{item.status}</span></div><small>{item.platformUserId || '未连接'}</small>{canWrite && <div className="actions">{['idle', 'disconnected'].includes(item.status) && <Button onClick={() => act(item.id, 'connect', item.status)}>连接</Button>}{['online', 'rate_limited'].includes(item.status) && <Button className="subtle" onClick={() => act(item.id, 'disconnected', item.status)}>标记离线</Button>}{item.status === 'disconnected' && <Button className="subtle" onClick={() => act(item.id, 'idle', item.status)}>释放账号</Button>}</div>}</article>)}</div></section>;
}
function AgentDetails({ run }: { run: AgentRun }) { const [detail, setDetail] = useState<AgentRun | null>(null); return <div className={`run ${run.status === 'blocked' ? 'blocked' : ''}`}><Button className="run-title" onClick={async () => setDetail(detail ? null : await client.getAgentRun({ id: run.id }))}>{run.id.slice(0, 8)} · {run.status} · {run.endReason || 'running'}</Button>{detail && <div className="steps">{detail.steps?.map((step, index) => <article key={index}><b>{index + 1}. {step.kind} {step.name || ''}</b><p>{step.resultSummary}</p>{step.auditVerdict && <small>审计：{step.auditVerdict}</small>}{step.errorCode && <small className="error">错误：{step.errorCode}</small>}{step.input && <pre>{JSON.stringify(step.input, null, 2)}</pre>}{step.kind === 'protocol_error' && <pre>{step.rawResponse}</pre>}</article>)}</div>}</div>; }
function GroupDetail({ id, canWrite, onClose }: { id: string; canWrite: boolean; onClose: () => void }) {
  const [group, setGroup] = useState<Group | null>(null); const [messages, setMessages] = useState<Message[]>([]); const [cursor, setCursor] = useState<string | null>(null); const [runs, setRuns] = useState<AgentRun[]>([]); const [accountId, setAccountId] = useState(''); const [text, setText] = useState(''); const [error, setError] = useState('');
  const refresh = async () => { try { const [g, page, recent] = await Promise.all([client.getGroup({ id }), client.listMessages({ id, limit: 50 }), client.listAgentRuns({ id })]); setGroup(g); setMessages(old => { const keys = new Set(page.items.map(item => item.clientMsgId || item.msgId)); return [...page.items, ...old.filter(item => !keys.has(item.clientMsgId || item.msgId))].sort((a,b) => String(b.sentAt).localeCompare(String(a.sentAt))); }); setCursor(page.nextCursor || null); setRuns(recent); setAccountId(old => old || g.members?.[0]?.accountId || ''); } catch (e) { setError(await errorText(e)); } };
  useEffect(() => { setMessages([]); void refresh(); }, [id]); useEvents(() => { void refresh(); });
  if (!group) return <section>加载群详情…</section>;
  return <section className="detail"><div className="section-title"><h2>群详情 <small>{id.slice(0, 8)}</small></h2><Button className="subtle" onClick={onClose}>关闭</Button></div>{error && <p className="error">{error}</p>}<div className="chips"><span>{group.status}</span><span>Agent：{group.agentEnabled ? '开启' : '关闭'}</span><span>自动移除：{group.autoKickEnabled ? '开启' : '关闭'}</span></div><h3>成员</h3><div className="members">{group.members?.map(member => <span key={member.accountId}>{member.accountId} · {member.role}</span>)}</div>{canWrite && <div className="toolbar"><Button className="subtle" onClick={async () => { await client.patchGroup({ id, groupPatch: { agentEnabled: !group.agentEnabled } }); refresh(); }}>切换 Agent</Button><Button className="subtle" onClick={async () => { await client.patchGroup({ id, groupPatch: { autoKickEnabled: !group.autoKickEnabled } }); refresh(); }}>切换自动移除</Button><Button className="danger" onClick={async () => { try { const job = await client.leaveAll({ id }); setError(`退群任务 ${job.jobId} 已开始`); refresh(); } catch (value) { setError(await errorText(value)); } }}>全部退群</Button><select value={accountId} onChange={e => setAccountId(e.target.value)}>{group.members?.map(member => <option value={member.accountId} key={member.accountId}>{member.accountId}</option>)}</select><Input value={text} onChange={e => setText(e.target.value)} placeholder="消息内容"/><Button onClick={async () => { try { await client.sendMessage({ id, sendRequest: { accountId, text } }); setText(''); refresh(); } catch (e) { setError(await errorText(e)); } }}>发送</Button></div>}<h3>消息时间线</h3><div className="timeline">{messages.map((message, index) => <div className={message.isOwn ? 'own' : ''} key={message.msgId || message.clientMsgId || index}><small>{message.sentAt} · {message.senderPlatformUserId}</small><p>{message.text}</p>{message.localFilePath && message.id && <Button className="subtle" onClick={async () => { try { const blob = await client.downloadMedia({ id: message.id! }); const url = URL.createObjectURL(blob); window.open(url, '_blank', 'noopener'); window.setTimeout(() => URL.revokeObjectURL(url), 60_000); } catch (value) { setError(await errorText(value)); } }}>查看附件</Button>}{message.isOwn && <em>{message.deliveryStatus}{message.failCode ? ` · ${message.failCode}` : ''}</em>}</div>)}</div>{cursor && <Button className="subtle" onClick={async () => { const page = await client.listMessages({ id, before: cursor, limit: 50 }); setMessages(old => [...old, ...page.items]); setCursor(page.nextCursor || null); }}>加载更早</Button>}<h3>Agent 运行</h3>{runs.map(run => <AgentDetails key={run.id} run={run} />)}</section>;
}
function App() { const [, redraw] = useState(0); const [groups, setGroups] = useState<Group[]>([]); const [accountsVersion, setAccountsVersion] = useState(0); const [selected, setSelected] = useState<string | null>(null); const session = currentSession(); const canWrite = session?.role === 'admin'; useEffect(() => { if (session) client.listGroups().then(setGroups); }, [!!session, selected]); if (!session) return <Login onReady={() => redraw(x => x + 1)} />; return <main><header><div><div className="brand">SENTINEL</div><h1>消息控制台</h1></div><span>{session.role}</span><Button className="subtle" onClick={async () => { try { await client.logout(); } finally { clearSession(); redraw(x => x + 1); } }}>退出</Button></header><Accounts canWrite={canWrite} onChanged={() => setAccountsVersion(value => value + 1)} />{canWrite && <GroupCreation refreshKey={accountsVersion} onCreated={async () => setGroups(await client.listGroups())} />}<section><div className="section-title"><h2>群组</h2><Button className="subtle" onClick={async () => setGroups(await client.listGroups())}>刷新</Button></div>{groups.map(group => <Button className="group-row" key={group.id} onClick={() => setSelected(group.id)}>{group.id.slice(0, 8)} <span>{group.status}</span> <small>Agent {group.agentEnabled ? 'on' : 'off'}</small></Button>)}</section>{selected && <><GroupDetail id={selected} canWrite={canWrite} onClose={() => setSelected(null)} />{canWrite && <SequencePanel groupId={selected} />}</>}</main>; }
createRoot(document.getElementById('root')!).render(<App />);
